version: "3.7"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: n8n_db_ut2k_user
      POSTGRES_PASSWORD: 3sapXElJd2b7rhQ76073WEkEEPeHyWz9
      POSTGRES_DB: n8n_db_ut2k
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    build: .
    restart: always
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=${DB_TYPE}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - SSL_EMAIL=${SSL_EMAIL}
      - N8N_EMAIL_MODE=${N8N_EMAIL_MODE}
      - N8N_SMTP_HOST=${N8N_SMTP_HOST}
      - N8N_SMTP_PORT=${N8N_SMTP_PORT}
      - N8N_SMTP_USER=${N8N_SMTP_USER}
      - N8N_SMTP_PASS=${N8N_SMTP_PASS}
      - N8N_SMTP_SENDER=${N8N_SMTP_SENDER}
      - N8N_SMTP_SSL=${N8N_SMTP_SSL}
    volumes:
      - n8n_data:/n8n/.n8n
    depends_on:
      - postgres

volumes:
  n8n_data:
  postgres_data:
